---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: training-operator
  name: training-operator
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - tfjobs
      - mxjobs
      - pytorchjobs
      - xgboostjobs
      - tfjobs/status
      - pytorchjobs/status
      - mxjobs/status
      - xgboostjobs/status
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - scheduling.volcano.sh
    resources:
      - podgroups
    verbs:
      - "*"
