---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: training-operator
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - -monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: public.ecr.aws/j1r0q0g6/training/training-operator
        name: training-operator
      serviceAccountName: training-operator
