apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ./crds
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
