# permissions for end users to edit mxjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mxjob-editor-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - mxjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - mxjobs/status
  verbs:
  - get
